# Use the latest 2.1 syntax.
version: 2.1

# Define a job for building and testing the .NET application.
jobs:
  build_and_test:
    # Use an official CircleCI Docker convenience image for the .NET SDK.
    # The `cimg/dotnet` family of images is recommended.
    # You can specify a version, e.g., `cimg/dotnet:7.0` or `cimg/dotnet:8.0`
    # Or use a specific version from the repository: https://hub.docker.com/r/cimg/dotnet/tags
    docker:
      - image: cimg/dotnet:8.0

    steps:
      - checkout
      
      # Restore dependencies
      - run:
          name: Restore dependencies
          command: dotnet restore

      # Build the application
      - run:
          name: Build the application
          command: dotnet build --configuration Release --no-restore

      # Run tests (assuming you have a test project)
      - run:
          name: Run tests
          command: dotnet test --no-restore --verbosity normal

# Define a workflow to run the job.
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
